void *upHaptic(void *vargp);
void *upTraffic(void *vargp);
void *upHeartBeat(void *vargp);
void *upTPO(void *vargp);
void *readGPS(void * arg);
void *readFile(void * arg);
void *readADSB(void * arg);
void *readHR(void * arg);
void *checkToggles(void* arg);
void haptic(int motorSelect, int wave1, int wave2, int wave3);
static gboolean _updateGPS();
double deg2rad(double inDeg);
static gboolean _update();
void on_btnStart_clicked();
void on_btnEnd_clicked();
void on_btnSet_clicked();
double CalcDist(double inLat,double inLong);
void on_tbActiveTraffic_clicked();
void rangeChange();
void *killThreads(void *args);
void on_btnClose_clicked();
void on_SSUI_destroy();
